reformat

diff --git a/Dockerfile.debian b/Dockerfile.debian
--- a/Dockerfile.debian
+++ b/Dockerfile.debian
@@ -10,127 +10,127 @@ ENV NGINX_VERSION 1.15.7-1~stretch
 ENV NJS_VERSION   1.15.7.0.2.6-1~stretch
 
 RUN set -x \
-	&& apt-get update \
-	&& apt-get install --no-install-recommends --no-install-suggests -y gnupg1 apt-transport-https ca-certificates \
-	&& \
-	NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
-	found=''; \
-	for server in \
-		ha.pool.sks-keyservers.net \
-		hkp://keyserver.ubuntu.com:80 \
-		hkp://p80.pool.sks-keyservers.net:80 \
-		pgp.mit.edu \
-	; do \
-		echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
-		apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
-	done; \
-	test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
-	apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
-	&& dpkgArch="$(dpkg --print-architecture)" \
-	&& nginxPackages=" \
-		nginx=${NGINX_VERSION} \
-		nginx-module-xslt=${NGINX_VERSION} \
-		nginx-module-geoip=${NGINX_VERSION} \
-		nginx-module-image-filter=${NGINX_VERSION} \
-		nginx-module-njs=${NJS_VERSION} \
-	" \
-	&& case "$dpkgArch" in \
-		amd64|i386) \
-# arches officialy built by upstream
-			echo "deb https://nginx.org/packages/mainline/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
-			&& apt-get update \
-			;; \
-		*) \
-# we're on an architecture upstream doesn't officially build for
-# let's build binaries from the published source packages
-			echo "deb-src https://nginx.org/packages/mainline/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
-			\
-# new directory for storing sources and .deb files
-			&& tempDir="$(mktemp -d)" \
-			&& chmod 777 "$tempDir" \
-# (777 to ensure APT's "_apt" user can access it too)
-			\
-# save list of currently-installed packages so build dependencies can be cleanly removed later
-			&& savedAptMark="$(apt-mark showmanual)" \
-			\
-# build .deb files from upstream's source packages (which are verified by apt-get)
-			&& apt-get update \
-			&& apt-get build-dep -y $nginxPackages \
-			&& ( \
-				cd "$tempDir" \
-				&& DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
-					apt-get source --compile $nginxPackages \
-			) \
-# we don't remove APT lists here because they get re-downloaded and removed later
-			\
-# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
-# (which is done after we install the built packages so we don't have to redownload any overlapping dependencies)
-			&& apt-mark showmanual | xargs apt-mark auto > /dev/null \
-			&& { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
-			\
-# create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
-			&& ls -lAFh "$tempDir" \
-			&& ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
-			&& grep '^Package: ' "$tempDir/Packages" \
-			&& echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
-# work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
-#   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
-#   ...
-#   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
-			&& apt-get -o Acquire::GzipIndexes=false update \
-			;; \
-	esac \
-	\
-	&& apt-get install --no-install-recommends --no-install-suggests -y \
-						$nginxPackages \
-						gettext-base \
-	&& apt-get remove --purge --auto-remove -y apt-transport-https ca-certificates && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
-	\
-# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
-	&& if [ -n "$tempDir" ]; then \
-		apt-get purge -y --auto-remove \
-		&& rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
-	fi
+  && apt-get update \
+  && apt-get install --no-install-recommends --no-install-suggests -y gnupg1 apt-transport-https ca-certificates \
+  && \
+  NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+  found=''; \
+  for server in \
+  ha.pool.sks-keyservers.net \
+  hkp://keyserver.ubuntu.com:80 \
+  hkp://p80.pool.sks-keyservers.net:80 \
+  pgp.mit.edu \
+  ; do \
+  echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+  apt-key adv --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+  done; \
+  test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+  apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
+  && dpkgArch="$(dpkg --print-architecture)" \
+  && nginxPackages=" \
+  nginx=${NGINX_VERSION} \
+  nginx-module-xslt=${NGINX_VERSION} \
+  nginx-module-geoip=${NGINX_VERSION} \
+  nginx-module-image-filter=${NGINX_VERSION} \
+  nginx-module-njs=${NJS_VERSION} \
+  " \
+  && case "$dpkgArch" in \
+  amd64|i386) \
+  # arches officialy built by upstream
+  echo "deb https://nginx.org/packages/mainline/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
+  && apt-get update \
+  ;; \
+  *) \
+  # we're on an architecture upstream doesn't officially build for
+  # let's build binaries from the published source packages
+  echo "deb-src https://nginx.org/packages/mainline/debian/ stretch nginx" >> /etc/apt/sources.list.d/nginx.list \
+  \
+  # new directory for storing sources and .deb files
+  && tempDir="$(mktemp -d)" \
+  && chmod 777 "$tempDir" \
+  # (777 to ensure APT's "_apt" user can access it too)
+  \
+  # save list of currently-installed packages so build dependencies can be cleanly removed later
+  && savedAptMark="$(apt-mark showmanual)" \
+  \
+  # build .deb files from upstream's source packages (which are verified by apt-get)
+  && apt-get update \
+  && apt-get build-dep -y $nginxPackages \
+  && ( \
+  cd "$tempDir" \
+  && DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
+  apt-get source --compile $nginxPackages \
+  ) \
+  # we don't remove APT lists here because they get re-downloaded and removed later
+  \
+  # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+  # (which is done after we install the built packages so we don't have to redownload any overlapping dependencies)
+  && apt-mark showmanual | xargs apt-mark auto > /dev/null \
+  && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
+  \
+  # create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
+  && ls -lAFh "$tempDir" \
+  && ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
+  && grep '^Package: ' "$tempDir/Packages" \
+  && echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
+  # work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
+  #   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+  #   ...
+  #   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+  && apt-get -o Acquire::GzipIndexes=false update \
+  ;; \
+  esac \
+  \
+  && apt-get install --no-install-recommends --no-install-suggests -y \
+  $nginxPackages \
+  gettext-base \
+  && apt-get remove --purge --auto-remove -y apt-transport-https ca-certificates && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
+  \
+  # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+  && if [ -n "$tempDir" ]; then \
+  apt-get purge -y --auto-remove \
+  && rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
+  fi
 
 # forward request and error logs to docker log collector
 RUN ln -sf /dev/stdout /var/log/nginx/access.log \
-	&& ln -sf /dev/stderr /var/log/nginx/error.log
+  && ln -sf /dev/stderr /var/log/nginx/error.log
 
 RUN apt-get update \
   && apt-get install --no-install-recommends --no-install-suggests -y \
-    supervisor \
-    wget \
-    certbot \
-    libssl-dev \
-    python-dev \
-    python-pip \
-    libffi-dev \
-    libfreetype6-dev \
-    libsqlite3-dev \
-    libmcrypt-dev \
-    libicu-dev \
-    libxslt-dev \
-		libzip-dev \
-    zip \
-    libjpeg62-turbo-dev && \
-    docker-php-ext-configure gd \
-      --with-gd \
-      --with-freetype-dir=/usr/include/ \
-      --with-png-dir=/usr/include/ \
-      --with-jpeg-dir=/usr/include/ && \
-		docker-php-ext-configure zip --with-libzip && \
-    docker-php-ext-install pdo_mysql mysqli gd exif intl xsl soap zip opcache && \
-    docker-php-source delete && \
-    mkdir -p /etc/nginx && \
-    mkdir -p /var/www/app && \
-    mkdir -p /run/nginx && \
-    mkdir -p /var/log/supervisor && \
-    EXPECTED_COMPOSER_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig) && \
-    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
-    php -r "if (hash_file('SHA384', 'composer-setup.php') === '${EXPECTED_COMPOSER_SIGNATURE}') { echo 'Composer.phar Installer verified'; } else { echo 'Composer.phar Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
-    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
-    php -r "unlink('composer-setup.php');"  && \
-    mkdir -p /etc/letsencrypt/webrootauth 
+  supervisor \
+  wget \
+  certbot \
+  libssl-dev \
+  python-dev \
+  python-pip \
+  libffi-dev \
+  libfreetype6-dev \
+  libsqlite3-dev \
+  libmcrypt-dev \
+  libicu-dev \
+  libxslt-dev \
+  libzip-dev \
+  zip \
+  libjpeg62-turbo-dev && \
+  docker-php-ext-configure gd \
+  --with-gd \
+  --with-freetype-dir=/usr/include/ \
+  --with-png-dir=/usr/include/ \
+  --with-jpeg-dir=/usr/include/ && \
+  docker-php-ext-configure zip --with-libzip && \
+  docker-php-ext-install pdo_mysql mysqli gd exif intl xsl soap zip opcache && \
+  docker-php-source delete && \
+  mkdir -p /etc/nginx && \
+  mkdir -p /var/www/app && \
+  mkdir -p /run/nginx && \
+  mkdir -p /var/log/supervisor && \
+  EXPECTED_COMPOSER_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig) && \
+  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
+  php -r "if (hash_file('SHA384', 'composer-setup.php') === '${EXPECTED_COMPOSER_SIGNATURE}') { echo 'Composer.phar Installer verified'; } else { echo 'Composer.phar Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
+  php composer-setup.php --install-dir=/usr/bin --filename=composer && \
+  php -r "unlink('composer-setup.php');"  && \
+  mkdir -p /etc/letsencrypt/webrootauth 
 #    ln -s /usr/bin/php7 /usr/bin/php
 
 RUN apt-get update && \
@@ -155,7 +155,7 @@ RUN apt-get update && \
   rm -r /var/lib/apt/lists/*
 
 RUN pecl install sqlsrv pdo_sqlsrv && \
-    docker-php-ext-enable sqlsrv pdo_sqlsrv
+  docker-php-ext-enable sqlsrv pdo_sqlsrv
 
 ADD conf/supervisord.conf /etc/supervisord.conf
 
@@ -165,35 +165,35 @@ ADD conf/nginx.conf /etc/nginx/nginx.conf
 
 # nginx site conf
 RUN mkdir -p /etc/nginx/sites-available/ && \
-mkdir -p /etc/nginx/sites-enabled/ && \
-mkdir -p /etc/nginx/ssl/ && \
-rm -Rf /var/www/* && \
-mkdir /var/www/html/
+  mkdir -p /etc/nginx/sites-enabled/ && \
+  mkdir -p /etc/nginx/ssl/ && \
+  rm -Rf /var/www/* && \
+  mkdir /var/www/html/
 ADD conf/nginx-site.conf /etc/nginx/sites-available/default.conf
 ADD conf/nginx-site-ssl.conf /etc/nginx/sites-available/default-ssl.conf
 RUN ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf
 
 # tweak php-fpm config
 RUN echo "cgi.fix_pathinfo=0" > ${php_vars} &&\
-    echo "upload_max_filesize = 100M"  >> ${php_vars} &&\
-    echo "post_max_size = 100M"  >> ${php_vars} &&\
-    echo "variables_order = \"EGPCS\""  >> ${php_vars} && \
-    echo "memory_limit = 128M"  >> ${php_vars} && \
-    sed -i \
-        -e "s/;catch_workers_output\s*=\s*yes/catch_workers_output = yes/g" \
-        -e "s/pm.max_children = 5/pm.max_children = 4/g" \
-        -e "s/pm.start_servers = 2/pm.start_servers = 3/g" \
-        -e "s/pm.min_spare_servers = 1/pm.min_spare_servers = 2/g" \
-        -e "s/pm.max_spare_servers = 3/pm.max_spare_servers = 4/g" \
-        -e "s/;pm.max_requests = 500/pm.max_requests = 200/g" \
-        -e "s/user = www-data/user = nginx/g" \
-        -e "s/group = www-data/group = nginx/g" \
-        -e "s/;listen.mode = 0660/listen.mode = 0666/g" \
-        -e "s/;listen.owner = www-data/listen.owner = nginx/g" \
-        -e "s/;listen.group = www-data/listen.group = nginx/g" \
-        -e "s/listen = 127.0.0.1:9000/listen = \/var\/run\/php-fpm.sock/g" \
-        -e "s/^;clear_env = no$/clear_env = no/" \
-        ${fpm_conf}
+  echo "upload_max_filesize = 100M"  >> ${php_vars} &&\
+  echo "post_max_size = 100M"  >> ${php_vars} &&\
+  echo "variables_order = \"EGPCS\""  >> ${php_vars} && \
+  echo "memory_limit = 128M"  >> ${php_vars} && \
+  sed -i \
+  -e "s/;catch_workers_output\s*=\s*yes/catch_workers_output = yes/g" \
+  -e "s/pm.max_children = 5/pm.max_children = 4/g" \
+  -e "s/pm.start_servers = 2/pm.start_servers = 3/g" \
+  -e "s/pm.min_spare_servers = 1/pm.min_spare_servers = 2/g" \
+  -e "s/pm.max_spare_servers = 3/pm.max_spare_servers = 4/g" \
+  -e "s/;pm.max_requests = 500/pm.max_requests = 200/g" \
+  -e "s/user = www-data/user = nginx/g" \
+  -e "s/group = www-data/group = nginx/g" \
+  -e "s/;listen.mode = 0660/listen.mode = 0666/g" \
+  -e "s/;listen.owner = www-data/listen.owner = nginx/g" \
+  -e "s/;listen.group = www-data/listen.group = nginx/g" \
+  -e "s/listen = 127.0.0.1:9000/listen = \/var\/run\/php-fpm.sock/g" \
+  -e "s/^;clear_env = no$/clear_env = no/" \
+  ${fpm_conf}
 #    ln -s /etc/php7/php.ini /etc/php7/conf.d/php.ini && \
 #    find /etc/php7/conf.d/ -name "*.ini" -exec sed -i -re 's/^(\s*)#(.*)/\1;\2/g' {} \;
 
